### PR TITLE
Update generated files for v1.1

### PR DESCRIPTION
**Pull request by yong24s**

### CODE REVIEW

**Comment by eugenepeh** [comment]
this is generated using https://github.com/reposense/RepoSense/pull/180?

**Comment by yong24s** [comment]
Yes. Also updated the js files using [reposense/RepoSense#187](https://github.com/reposense/RepoSense/pull/187 ).

GitHub pages is up https://yong24s.github.io/dashboard-demo/

**Comment by eugenepeh** [comment]
@yong24s please add back the config.csv

**Comment by eugenepeh** [comment]
@yong24s config file missing again 🤣

**Pull request merged**
